apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-springboot-deployment
  labels:
    app: k8s-springboot-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-springboot-deployment
      labels:
        app: k8s-springboot-deployment
    spec:
      containers:
        - name: k8s-springboot-deployment
          image: lgedu/k8s-springboot:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: DB_DRIVER_NAME
              value: "com.mysql.jdbc.Driver"
            - name: DB_USER_NAME
              value: "root"
            - name: DB_URL
              value: "jdbc:mysql://192.168.238.182:30036/lagou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8"
      restartPolicy: Always
  selector:
    matchLabels:
      app: k8s-springboot-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-springboot-service
spec:
  selector:
    app: k8s-springboot-deployment
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
  type: NodePort
